# List all the drivers
all: undirectedGraphdriver
 
undirectedGraphdriver: undirectedGraphtest.cpp
	g++ -std=c++11 -o  undirectedGraphdriver undirectedGraphtest.cpp

# List all the executables under 'all:'
clean:
	rm undirectedGraphdriver 
